export {default as Main} from './main/Main'
export {default as Home} from './home/Home'
export {default as About} from './about/About'
export {default as Resume} from  './resume/Resume'
export {default as Contact} from  './contact-me/Contact'